// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconfontIcon: typeof import('./src/components/IconfontIcon.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    ThirdLink: typeof import('./src/components/ThirdLink.vue')['default']
    UiScrollbars: typeof import('./src/components/Ui/Scrollbars.vue')['default']
    UiTippy: typeof import('./src/components/Ui/Tippy.vue')['default']
    UiTippyer: typeof import('./src/components/Ui/Tippyer.vue')['default']
    UiX: typeof import('./src/components/Ui/X.vue')['default']
  }
}

export {}
