// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    DashboardCoreTraitsRank: typeof import('./src/components/Dashboard/CoreTraitsRank.vue')['default']
    DashboardItems: typeof import('./src/components/Dashboard/Items.vue')['default']
    DashboardTradeHistory: typeof import('./src/components/Dashboard/TradeHistory.vue')['default']
    DashboardTraitsHistory: typeof import('./src/components/Dashboard/TraitsHistory.vue')['default']
    DashboardWhales: typeof import('./src/components/Dashboard/Whales.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconfontIcon: typeof import('./src/components/IconfontIcon.vue')['default']
    MbSideBar: typeof import('./src/components/MbSideBar.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    ThirdLink: typeof import('./src/components/ThirdLink.vue')['default']
    UiDropdown: typeof import('./src/components/Ui/Dropdown.vue')['default']
    UiImg: typeof import('./src/components/Ui/Img.vue')['default']
    UiScrollbars: typeof import('./src/components/Ui/Scrollbars.vue')['default']
    UiTabs: typeof import('./src/components/Ui/Tabs.vue')['default']
    UiTippyer: typeof import('./src/components/Ui/Tippyer.vue')['default']
  }
}

export {}
